# Generated by Django 2.2 on 2019-04-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20190415_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='used_invitations',
            new_name='user_invitations',
        ),
    ]
